[0m13:29:20.301330 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71fd6e230e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71fd6cc74a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71fd6cc76bc0>]}


============================== 13:29:20.309945 | 00a91ea6-e5cc-4b61-a4fb-013de7e9930e ==============================
[0m13:29:20.309945 [info ] [MainThread]: Running with dbt=1.10.3
[0m13:29:20.312369 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/mohamed-client/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init dbt_financial_txns', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:29:20.363393 [info ] [MainThread]: Creating dbt configuration folder at /home/mohamed-client/.dbt
[0m13:29:20.370092 [debug] [MainThread]: Starter project path: /home/mohamed-client/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m13:29:20.390131 [info ] [MainThread]: 
Your new dbt project "dbt_financial_txns" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:29:20.396093 [info ] [MainThread]: Setting up your profile.
[0m13:36:53.960257 [error] [MainThread]: Encountered an error:

[0m13:36:53.969187 [error] [MainThread]: Traceback (most recent call last):
  File "/home/mohamed-client/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/mohamed-client/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/home/mohamed-client/.local/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/home/mohamed-client/.local/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/mohamed-client/.local/lib/python3.10/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/home/mohamed-client/.local/lib/python3.10/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/usr/lib/python3/dist-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
  File "/usr/lib/python3/dist-packages/click/termui.py", line 150, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m13:36:53.975096 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 453.86526, "process_in_blocks": "960", "process_kernel_time": 0.304385, "process_mem_max_rss": "92644", "process_out_blocks": "72", "process_user_time": 4.69189}
[0m13:36:53.978560 [debug] [MainThread]: Command `dbt init` failed at 13:36:53.977376 after 453.87 seconds
[0m13:36:53.980779 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71fd6e230e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71fd6cc74220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71fd6ccf8130>]}
[0m13:36:53.982199 [debug] [MainThread]: Flushing usage events
[0m13:36:54.910715 [debug] [MainThread]: An error was encountered while trying to flush usage events
